---

- hosts: webservers
  gather_facts: no

  roles:
    - role: geerlingguy.pip
      tags: pip

    - role: datadog.datadog
      become: yes
      tags: datadog

  tasks:
    - name: Start Redmine
      community.docker.docker_container:
        name: app
        image: redmine
        restart_policy: always
        state: started
        ports:
          - 8080:3000
        env:
          REDMINE_DB_POSTGRES: "{{ redmine_db_host }}"
          REDMINE_DB_PORT: "{{ redmine_db_port | string }}"
          REDMINE_DB_USERNAME: "{{ redmine_db_username }}"
          REDMINE_DB_PASSWORD: "{{ redmine_db_password }}"
          REDMINE_DB_DATABASE: "{{ redmine_db_database }}"

